/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

public class ubahdata extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ubahdata.class.getName());

    private int idKonten;

    public ubahdata() {
        initComponents();
    }

    public void kirimDataLama(int id, String judul, String kategori, String platform, String tanggal, String status) {
    this.idKonten = id; 
    
    txtjudulU.setText(judul);
    cbkategoriU.setSelectedItem(kategori);
    cbplatformU.setSelectedItem(platform);
    cbstatusU.setSelectedItem(status);
    
    try {
        java.util.Date date = new java.text.SimpleDateFormat("yyyy-MM-dd").parse(tanggal);
        jadwalU.setDate(date);
    } catch (Exception e) {
        System.out.println("Gagal memat tanggal: " + e.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jadwal = new de.wannawork.jcalendar.JCalendarComboBox();
        kategori = new javax.swing.JComboBox<>();
        txtjudul = new javax.swing.JTextField();
        cbstatus = new javax.swing.JComboBox<>();
        cbplatform = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        jadwalU = new de.wannawork.jcalendar.JCalendarComboBox();
        btnBatal = new javax.swing.JButton();
        btnTutup = new javax.swing.JButton();
        cbkategoriU = new javax.swing.JComboBox<>();
        txtjudulU = new javax.swing.JTextField();
        cbstatusU = new javax.swing.JComboBox<>();
        cbplatformU = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Edukasi ", "Hiburan ", "Game ", "Musik", "Promosi", "Review" }));
        kategori.addActionListener(this::kategoriActionPerformed);

        txtjudul.addActionListener(this::txtjudulActionPerformed);

        cbstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Draft", "Produksi", "Siap Tayang ", "Selesai" }));

        cbplatform.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platform", "Instagram", "TikTok", "YouTube", "X (Twitter)" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("UBAH DATA");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(this::btnUbahActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        btnTutup.setText("Tutup");
        btnTutup.addActionListener(this::btnTutupActionPerformed);

        cbkategoriU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kategori", "Edukasi ", "Hiburan ", "Game ", "Musik", "Promosi", "Review" }));
        cbkategoriU.addActionListener(this::cbkategoriUActionPerformed);

        txtjudulU.addActionListener(this::txtjudulUActionPerformed);

        cbstatusU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "Draft", "Produksi", "Siap Tayang ", "Selesai" }));

        cbplatformU.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Platform", "Instagram", "TikTok", "YouTube", "X (Twitter)" }));
        cbplatformU.addActionListener(this::cbplatformUActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jadwalU, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                        .addGap(230, 230, 230))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnUbah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnTutup))
                    .addComponent(cbstatusU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtjudulU)
                    .addComponent(cbkategoriU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbplatformU, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtjudulU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbkategoriU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbplatformU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jadwalU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbstatusU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUbah)
                    .addComponent(btnBatal)
                    .addComponent(btnTutup))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriActionPerformed

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
       String judul = txtjudulU.getText().trim();
    int idKategori = cbkategoriU.getSelectedIndex(); 
    int idPlatform = cbplatformU.getSelectedIndex(); 
    String status = cbstatusU.getSelectedItem().toString();
    
    String tanggal = "";
    if (jadwal.getDate() != null) {
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
        tanggal = sdf.format(jadwal.getDate());
    }

    if (judul.isEmpty() || idKategori == 0 || idPlatform == 0 || tanggal.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Semua data input harus dilengkapi!");
        return;
    }

    control.kontencontrol cc = new control.kontencontrol();
    boolean berhasil = cc.ubahKonten(idKonten, judul, idKategori, idPlatform, tanggal, status);

    if (berhasil) {
        javax.swing.JOptionPane.showMessageDialog(this, "Perubahan data berhasil disimpan ke database!");
        this.dispose(); 
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal memperbarui data database.");
    }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        txtjudulU.setText("");
        kategori.setSelectedIndex(0);
        cbplatformU.setSelectedIndex(0);
        cbstatusU.setSelectedIndex(0);
        jadwalU.setDate(null);
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void cbkategoriUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoriUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbkategoriUActionPerformed

    private void txtjudulUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulUActionPerformed

    private void cbplatformUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbplatformUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbplatformUActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTutup;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cbkategoriU;
    private javax.swing.JComboBox<String> cbplatform;
    private javax.swing.JComboBox<String> cbplatformU;
    private javax.swing.JComboBox<String> cbstatus;
    private javax.swing.JComboBox<String> cbstatusU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private de.wannawork.jcalendar.JCalendarComboBox jadwal;
    private de.wannawork.jcalendar.JCalendarComboBox jadwalU;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtjudulU;
    // End of variables declaration//GEN-END:variables
}
